---
# FantasyPlus Configuration! By Enrick3344
# You Can Use & For The Color Codes.

# The Prefix That Will Be Used For The Protection Part Of The Plugin.
Prefix: §7[§dFantasyProtection§7]

# Protection Configuration!
Hunger: []
Break: []
Break-Message: §cYou are not allow to break blocks here!
Place: []
Place-Message: §cYou are not allow to place blocks here!
Lock: []
Lock-Message: §cYou are not allow to do that here!
Drop: []
Drop-Message: §cYou are not allow to drop items or blocks here!
PVP: []
PVP-Message: §cYou are not allow to PVP here!

# Freeze Command Configuration!
Freeze-Popup-Message: §l§5>§r§d You Are Frozen!

# Chat Command Configuration!
Disable-Chat: false

# NoTPA Command Configuration!
NoTPA: []
...
