---
Prefix: §7[§dFantasyProtection§7]
Hunger: []
Break: []
Break-Message: §cYou are not aloud to break blocks here!
Place: []
Place-Message: §cYou are not aloud to place blocks here!
Drop: []
Drop-Message: §cYou are not aloud to drop items or blocks here!
...
