---
Prefix: §7[§dFantasyProtection§7]
Hunger:
- world
Break:
- world
Break-Message: §cYou are not aloud to break blocks here!
Place:
- world
Place-Message: §cYou are not aloud to place blocks here!
Drop:
- world
- Plot
- HG
- world2
Drop-Message: §cYou are not aloud to drop items or blocks here!
...
